name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - java-backend/**
      - .github/workflows/backend-build.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - java-backend/**
      - .github/workflows/backend-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file java-backend/pom.xml
    - name: Archive jar
      uses: actions/upload-artifact@v4
      with:
        name: quarkus-app
        path: java-backend/target/quarkus-app