name: Angular CI

on:
  push:
    branches: [ "main" ]
    paths:
      - angular-frontend/**
      - .github/workflows/frontend-build.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - angular-frontend/**
      - .github/workflows/frontend-build.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: angular-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup Angular
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Test Angular Project
        run: npm run test -- --browsers=ChromeHeadless --watch=false

  lint:
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: angular-frontend
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
     - name: Setup Angular
       run: npm install -g @angular/cli
     - name: Install Dependencies
       run: npm install
     - name: Lint Angular Project
       run: npm run lint

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup Angular
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Check Format Angular Project
        run: npx prettier -w .

  build:
    runs-on: ubuntu-latest
    needs: [lint, format, test]
    defaults:
      run:
        working-directory: angular-frontend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - name: Setup Angular
      run: npm install -g @angular/cli
    - name: Install Dependencies
      run: npm install
    - name: Check Format Angular Project
      run: npm run build --prod
    - name: Archive build bundle
      uses: actions/upload-artifact@v4
      with:
        name: angular-frontend
        path: angular-frontend/dist/angular-frontend